
import type { Product, User, Category, Auction } from '@/lib/types';

export const users: User[] = [
  {
    id: 'user_1',
    name: 'Elena',
    avatarUrl: 'https://picsum.photos/seed/elena/200/200',
    storeName: "Elena's Emporium",
    bio: 'Creating beautiful, handcrafted items with love and passion. Each piece tells a story.',
    privateCollectionPassword: 'password123',
    birthDate: '1985-03-15',
    postcode: '2000',
  },
  {
    id: 'user_2',
    name: 'Marcus',
    avatarUrl: 'https://picsum.photos/seed/marcus/200/200',
    storeName: 'Modern Designs',
    bio: 'Sleek, modern designs for the contemporary home. Functionality meets art.',
    birthDate: '1990-07-22',
    friendIds: ['user_1'], // Marcus is friends with Elena
    blockedSellerIds: ['user_3'], // Marcus has blocked Anya
    postcode: '3000',
  },
  {
    id: 'user_3',
    name: 'Anya',
    avatarUrl: 'https://picsum.photos/seed/anya/200/200',
    storeName: 'Vintage Finds',
    bio: 'Curating timeless pieces from the past. Discover treasures with history.',
    birthDate: '2008-11-10', // Under 18
    postcode: '4000',
  },
];

export const categories: Category[] = [
  {
    id: 'cat_1',
    name: 'Handmade',
    slug: 'handmade',
    description: 'Unique, handcrafted items made by artisans.',
  },
  {
    id: 'cat_2',
    name: 'Vintage',
    slug: 'vintage',
    description: 'Timeless pieces and curated finds from the past.',
  },
  {
    id: 'cat_3',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Decor, furniture, and more to beautify your space.',
  },
  {
    id: 'cat_4',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Apparel, accessories, and unique style.',
  },
  {
    id: 'cat_5',
    name: 'Collector Cards',
    slug: 'collector-cards',
    description: 'Trading cards, sports cards, and other collectible cards.',
  },
];

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Vintage Leather Jacket',
    description:
      'A classic brown leather jacket from the 80s, in excellent condition. Features a worn-in feel for authentic vintage style.',
    price: 185.0,
    category: 'Vintage',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/leatherjacket/600/800'],
    imageHint: 'leather jacket',
  },
  {
    id: 'prod_2',
    name: 'Handmade Ceramic Mug',
    description:
      'A beautiful, hand-thrown ceramic mug with a speckled blue glaze. Perfect for your morning coffee or tea. Microwave and dishwasher safe.',
    price: 35.0,
    category: 'Handmade',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/ceramicmug/600/600'],
    imageHint: 'ceramic mug',
  },
  {
    id: 'prod_3',
    name: 'Abstract Canvas Art',
    description:
      'Large, original abstract painting on canvas. A vibrant mix of colors to make a statement in any room. Signed by the artist.',
    price: 320.0,
    category: 'Home & Living',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/abstractart/800/600'],
    imageHint: 'abstract art',
  },
  {
    id: 'prod_4',
    name: 'Minimalist Wall Clock',
    description:
      'A sleek and modern wall clock with a natural wood frame and silent quartz movement. Adds a touch of elegance to your home.',
    price: 75.0,
    category: 'Home & Living',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/wallclock/600/600'],
    imageHint: 'wall clock',
  },
  {
    id: 'prod_5',
    name: 'Holographic Dragon Card',
    description:
      'A rare, holographic dragon trading card from the limited first edition set. Mint condition.',
    price: 88.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: [
      'https://picsum.photos/seed/dragoncard/400/560',
      'https://picsum.photos/seed/dragoncard2/400/560',
      'https://picsum.photos/seed/dragoncard3/400/560',
      'https://picsum.photos/seed/dragoncard4/400/560',
      'https://picsum.photos/seed/dragoncard5/400/560',
    ],
    imageHint: 'holographic card',
  },
  {
    id: 'prod_6',
    name: 'Handcrafted Silver Rings',
    description:
      'A set of three stackable silver rings, hammered for a unique texture. Made from 925 sterling silver. Available in multiple sizes.',
    price: 95.0,
    category: 'Fashion',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/silverrings/600/600'],
    imageHint: 'silver rings',
  },
  {
    id: 'prod_7',
    name: 'Modern Wooden Desk Lamp',
    description:
      'An adjustable desk lamp made from light oak wood with a minimalist design. Provides warm, focused light for your workspace.',
    price: 110.0,
    category: 'Home & Living',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/desklamp/600/800'],
    imageHint: 'desk lamp',
  },
  {
    id: 'prod_8',
    name: 'Rookie Sports Card',
    description:
      'A highly sought-after rookie card of a star athlete. Graded PSA 9.',
    price: 450.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/sportscard/400/560'],
    imageHint: 'sports card',
  },
  {
    id: 'prod_9',
    name: 'Vintage Record Player',
    description:
      'A fully functional 1970s turntable in a wooden case. A beautiful piece for any vinyl enthusiast. Serviced and tested.',
    price: 250.0,
    category: 'Vintage',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/recordplayer/700/600'],
    imageHint: 'record player',
  },
  {
    id: 'prod_10',
    name: 'Gourmet Coffee Beans',
    description:
      'Single-origin Ethiopian Yirgacheffe coffee beans, medium roast. Notes of citrus and floral. Whole beans, 12oz bag.',
    price: 22.0,
    category: 'Handmade',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/coffeebeans/600/600'],
    imageHint: 'coffee beans',
  },
  {
    id: 'prod_11',
    name: 'Private Collection Vase',
    description: 'An exclusive, one-of-a-kind vase for our special customers.',
    price: 500.0,
    category: 'Handmade',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/privatevase/600/600'],
    imageHint: 'exclusive vase',
    isPrivate: true,
  },
  {
    id: 'prod_12',
    name: 'Limited Edition Scarf',
    description: 'A limited run scarf, made from the finest silk.',
    price: 250.0,
    category: 'Fashion',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/privatescarf/600/600'],
    imageHint: 'silk scarf',
    isPrivate: true,
  },
  {
    id: 'prod_13',
    name: 'Charizard Collector Card',
    description: 'The iconic Charizard card from the base set. A must-have for any collector.',
    price: 350.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/charizard/400/560'],
    imageHint: 'fire dragon',
  },
  {
    id: 'prod_14',
    name: 'Pikachu Illustrator Card',
    description: 'An extremely rare Pikachu Illustrator promo card. One of the holy grails of card collecting.',
    price: 5275000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/pikachu/400/560'],
    imageHint: 'electric mouse',
  },
  {
    id: 'prod_15',
    name: 'Michael Jordan Rookie Card',
    description: '1986 Fleer Michael Jordan rookie card. The cornerstone of any basketball card collection.',
    price: 720000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/jordan/400/560'],
    imageHint: 'basketball player',
  },
  {
    id: 'prod_16',
    name: 'Honus Wagner T206 Card',
    description: 'The T206 Honus Wagner, the most famous baseball card in the world.',
    price: 6600000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/wagner/400/560'],
    imageHint: 'baseball player',
  },
  {
    id: 'prod_17',
    name: 'Black Lotus Magic Card',
    description: 'Black Lotus from Alpha set of Magic: The Gathering. A piece of gaming history.',
    price: 511100.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/lotus/400/560'],
    imageHint: 'black flower',
  },
  {
    id: 'prod_18',
    name: 'Wayne Gretzky Rookie Card',
    description: '1979 O-Pee-Chee Wayne Gretzky rookie card. The great one\'s debut.',
    price: 3750000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/gretzky/400/560'],
    imageHint: 'hockey player',
  },
  {
    id: 'prod_19',
    name: 'Mickey Mantle 1952 Topps',
    description: 'The iconic 1952 Topps Mickey Mantle. A legendary card.',
    price: 12600000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/mantle/400/560'],
    imageHint: 'baseball legend',
  },
  {
    id: 'prod_20',
    name: 'Kobe Bryant Rookie Auto',
    description: '1996-97 Topps Chrome Refractor with on-card autograph. PSA 10.',
    price: 1795000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/kobe-rookie/400/560'],
    imageHint: 'basketball star',
  },
  {
    id: 'prod_21',
    name: 'Patrick Mahomes Kaboom!',
    description: '2017 Panini Kaboom! Gold insert. Extremely rare.',
    price: 500000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/mahomes-kaboom/400/560'],
    imageHint: 'football qb',
  },
  {
    id: 'prod_22',
    name: 'Cristiano Ronaldo CR7',
    description: '2002 Panini Futebol Portugal rookie card. The debut of a legend.',
    price: 312000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/ronaldo-rookie/400/560'],
    imageHint: 'soccer star',
  },
  {
    id: 'prod_23',
    name: 'Blastoise 1st Edition',
    description: '1st Edition Shadowless Holo Blastoise from the Base Set. PSA 9.',
    price: 25000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/blastoise/400/560'],
    imageHint: 'water turtle',
  },
  {
    id: 'prod_24',
    name: 'Tom Brady Championship Ticket',
    description: '2000 Playoff Contenders Championship Ticket autograph rookie card. /100',
    price: 3107000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/brady-rookie/400/560'],
    imageHint: 'nfl goat',
  },
  {
    id: 'prod_25',
    name: 'Lugia 1st Edition Neo Genesis',
    description: 'The iconic holographic Lugia from Neo Genesis. Graded BGS 10 Pristine.',
    price: 144300.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/lugia-neo/400/560'],
    imageHint: 'sea monster',
  },
  {
    id: 'prod_26',
    name: 'Stephen Curry Logoman Auto',
    description: '2009/10 Panini National Treasures Logoman Autograph 1/1.',
    price: 5900000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/curry-logoman/400/560'],
    imageHint: 'nba shooter',
  },
  {
    id: 'prod_27',
    name: 'Time Walk - MTG Alpha',
    description: 'A powerhouse from Magic: The Gathering\'s first set, Alpha. BGS 9.',
    price: 28000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/time-walk/400/560'],
    imageHint: 'magic spell',
  },
  {
    id: 'prod_28',
    name: 'Shohei Ohtani Superfractor',
    description: '2018 Bowman Chrome Superfractor Autograph 1/1. A modern grail.',
    price: 186000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/ohtani-super/400/560'],
    imageHint: 'baseball mvp',
  },
  {
    id: 'prod_29',
    name: 'Gengar 1st Edition Skyridge',
    description: 'The highly sought-after holographic Gengar from the Skyridge set.',
    price: 8500.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/gengar-skyridge/400/560'],
    imageHint: 'ghost pokemon',
  },
  {
    id: 'prod_30',
    name: 'Joe Burrow NFL Shield',
    description: '2020 Panini Prizm Black Finite NFL Shield Autograph 1/1.',
    price: 250000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/burrow-shield/400/560'],
    imageHint: 'football player',
  },
  {
    id: 'prod_31',
    name: 'Mox Sapphire - MTG Beta',
    description: 'From the Power Nine, a Beta Mox Sapphire. BGS 8.5.',
    price: 15000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/mox-sapphire/400/560'],
    imageHint: 'blue gem',
  },
  {
    id: 'prod_32',
    name: 'Zion Williamson Nebula',
    description: '2019 Panini Prizm Nebula Autograph 1/1. An incredible Zion rookie.',
    price: 98000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/zion-nebula/400/560'],
    imageHint: 'basketball dunker',
  },
  {
    id: 'prod_33',
    name: 'Umbreon Gold Star',
    description: 'The iconic Gold Star Umbreon from POP Series 5. PSA 10.',
    price: 70000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/umbreon-goldstar/400/560'],
    imageHint: 'dark pokemon',
  },
  {
    id: 'prod_34',
    name: 'Pele 1958 Alifabolaget',
    description: 'The true rookie card of the greatest soccer player of all time. PSA 8.',
    price: 1350000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/pele-rookie/400/560'],
    imageHint: 'soccer legend',
  },
  {
    id: 'prod_35',
    name: 'Jasson Dominguez Superfractor',
    description: '2020 Bowman Chrome Prospect Auto Superfractor 1/1. "The Martian".',
    price: 474000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/dominguez-super/400/560'],
    imageHint: 'baseball prospect',
  },
  {
    id: 'prod_36',
    name: 'Tyranitar 1st Edition Neo',
    description: 'Holographic Tyranitar from Neo Discovery. A fan favorite.',
    price: 1200.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/tyranitar-neo/400/560'],
    imageHint: 'dinosaur pokemon',
  },
  {
    id: 'prod_37',
    name: 'Ancestral Recall - MTG Alpha',
    description: 'Alpha Ancestral Recall, part of the Power Nine. BGS graded.',
    price: 18000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/ancestral-recall/400/560'],
    imageHint: 'magic card',
  },
  {
    id: 'prod_38',
    name: 'Luka Doncic Logoman Auto',
    description: '2018 Panini National Treasures Logoman Autograph 1/1. A modern masterpiece.',
    price: 4600000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/luka-logoman/400/560'],
    imageHint: 'basketball pointguard',
  },
  {
    id: 'prod_39',
    name: 'Dark Charizard Holo 1st Edition',
    description: 'From the Team Rocket set, the iconic Dark Charizard. PSA 10.',
    price: 7500.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/dark-charizard/400/560'],
    imageHint: 'dark dragon',
  },
  {
    id: 'prod_40',
    name: 'Justin Herbert Shield Auto',
    description: '2020 Panini Contenders Optic NFL Shield Autograph 1/1.',
    price: 180000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/herbert-shield/400/560'],
    imageHint: 'quarterback nfl',
  },
  {
    id: 'prod_41',
    name: 'Shining Charizard Neo Destiny',
    description: '1st Edition Shining Charizard from Neo Destiny. A true gem.',
    price: 22000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/shining-charizard/400/560'],
    imageHint: 'shiny dragon',
  },
  {
    id: 'prod_42',
    name: 'Giannis Antetokounmpo Prizm Black',
    description: '2013 Panini Prizm Black Prizm Autograph 1/1 rookie card.',
    price: 1100000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/giannis-prizm/400/560'],
    imageHint: 'greek freak',
  },
  {
    id: 'prod_43',
    name: 'Volcanic Island - MTG Beta',
    description: 'A key dual land from the Beta set of Magic: The Gathering.',
    price: 9500.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/volcanic-island/400/560'],
    imageHint: 'island volcano',
  },
  {
    id: 'prod_44',
    name: 'Crystal Charizard Skyridge',
    description: 'Reverse Holo Crystal Charizard from the e-Reader series.',
    price: 15000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/crystal-charizard/400/560'],
    imageHint: 'crystal dragon',
  },
  {
    id: 'prod_45',
    name: 'Erling Haaland Auto',
    description: '2019 Topps Chrome Bundesliga Autograph rookie card of the phenom.',
    price: 8000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/haaland-auto/400/560'],
    imageHint: 'soccer striker',
  },
  {
    id: 'prod_46',
    name: 'Rayquaza Gold Star',
    description: 'The elusive Gold Star Rayquaza from EX Deoxys. PSA 10.',
    price: 45000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/rayquaza-star/400/560'],
    imageHint: 'sky dragon',
  },
  {
    id: 'prod_47',
    name: 'Mike Trout Prospect Auto',
    description: '2009 Bowman Chrome Draft Prospects Autograph. The modern-day Mickey Mantle.',
    price: 3900000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/trout-auto/400/560'],
    imageHint: 'baseball outfielder',
  },
  {
    id: 'prod_48',
    name: 'Underground Sea - MTG Alpha',
    description: 'The most powerful dual land from Alpha. Graded BGS 9.5.',
    price: 100000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/underground-sea/400/560'],
    imageHint: 'dark sea',
  },
  {
    id: 'prod_49',
    name: 'Venusaur 1st Edition',
    description: '1st Edition Shadowless Holo Venusaur from the Base Set. PSA 9.',
    price: 8000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/venusaur/400/560'],
    imageHint: 'flower dinosaur',
  },
  {
    id: 'prod_50',
    name: 'LeBron James Exquisite RPA',
    description: '2003-04 Upper Deck Exquisite Rookie Patch Autograph /99.',
    price: 5200000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/lebron-rpa/400/560'],
    imageHint: 'king james',
  },
  {
    id: 'prod_51',
    name: 'Gaea\'s Cradle - Urza\'s Saga',
    description: 'A legendary land that is a staple in many Magic formats.',
    price: 800.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/gaeas-cradle/400/560'],
    imageHint: 'forest land',
  },
  {
    id: 'prod_52',
    name: 'Kylian Mbappe Rookie Auto',
    description: '2016 Panini Foot Autograph of the French superstar.',
    price: 15000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/mbappe-auto/400/560'],
    imageHint: 'french forward',
  },
  {
    id: 'prod_53',
    name: 'Espeon Gold Star',
    description: 'POP Series 5 Gold Star Espeon, one of the rarest Eeveelutions.',
    price: 25000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/espeon-star/400/560'],
    imageHint: 'psychic pokemon',
  },
  {
    id: 'prod_54',
    name: 'Justin Jefferson Kaboom!',
    description: '2020 Panini Kaboom! rookie insert. A fan favorite.',
    price: 3500.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/jefferson-kaboom/400/560'],
    imageHint: 'nfl receiver',
  },
  {
    id: 'prod_55',
    name: 'Mewtwo 1st Edition',
    description: '1st Edition Shadowless Holo Mewtwo from the Base Set. PSA 10.',
    price: 20000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/mewtwo/400/560'],
    imageHint: 'genetic pokemon',
  },
  {
    id: 'prod_56',
    name: 'LaMelo Ball Gold Prizm',
    description: '2020 Panini Prizm Gold Shimmer Rookie Autograph /10.',
    price: 45000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/lamelo-gold/400/560'],
    imageHint: 'nba guard',
  },
  {
    id: 'prod_57',
    name: 'Tropical Wind - TCG Promo',
    description: 'Extremely rare Tropical Wind promo card from the TCG World Championships.',
    price: 65000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/tropical-wind/400/560'],
    imageHint: 'pokemon trophy',
  },
  {
    id: 'prod_58',
    name: 'Force of Will - Alliances',
    description: 'The iconic blue instant from Alliances. A staple in eternal formats.',
    price: 100.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/force-of-will/400/560'],
    imageHint: 'blue spell',
  },
  {
    id: 'prod_59',
    name: 'Connor McDavid Young Guns',
    description: '2015-16 Upper Deck Young Guns rookie card of the NHL superstar.',
    price: 1500.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/mcdavid-yg/400/560'],
    imageHint: 'hockey star',
  },
  {
    id: 'prod_60',
    name: 'Alakazam 1st Edition',
    description: '1st Edition Shadowless Holo Alakazam from the Base Set. PSA 9.',
    price: 4500.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/alakazam/400/560'],
    imageHint: 'spoon bender',
  },
  {
    id: 'prod_61',
    name: 'Anthony Edwards Flawless RPA',
    description: '2020 Panini Flawless Rookie Patch Autograph /25.',
    price: 12000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/ant-rpa/400/560'],
    imageHint: 'nba dunker',
  },
  {
    id: 'prod_62',
    name: 'Tundra - MTG Beta',
    description: 'A Beta dual land, essential for any serious Magic collector.',
    price: 6000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/tundra-beta/400/560'],
    imageHint: 'ice land',
  },
  {
    id: 'prod_63',
    name: 'Gold Star Jolteon',
    description: 'The vibrant Gold Star Jolteon from POP Series 5. Very rare.',
    price: 8000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/jolteon-star/400/560'],
    imageHint: 'electric pokemon',
  },
  {
    id: 'prod_64',
    name: 'Trevor Lawrence Downtown',
    description: '2021 Panini Donruss Downtown rookie insert. Highly collectible.',
    price: 2500.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/lawrence-downtown/400/560'],
    imageHint: 'nfl qb',
  },
  {
    id: 'prod_65',
    name: 'Gyarados 1st Edition',
    description: '1st Edition Shadowless Holo Gyarados from the Base Set. PSA 9.',
    price: 3500.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/gyarados/400/560'],
    imageHint: 'sea serpent',
  },
  {
    id: 'prod_66',
    name: 'Jayson Tatum Color Blast',
    description: '2019 Panini Prizm Color Blast insert. A beautiful and rare card.',
    price: 9000.0,
    category: 'Collector Cards',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/tatum-colorblast/400/560'],
    imageHint: 'celtics star',
  },
  {
    id: 'prod_67',
    name: 'Vaporeon Gold Star',
    description: 'The elusive Gold Star Vaporeon from POP Series 5. Graded PSA 10.',
    price: 18000.0,
    category: 'Collector Cards',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/vaporeon-star/400/560'],
    imageHint: 'water pokemon',
  },
  {
    id: 'prod_68',
    name: 'Sidney Crosby The Cup RPA',
    description: '2005-06 Upper Deck The Cup Rookie Patch Autograph /99.',
    price: 150000.0,
    category: 'Collector Cards',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/crosby-cup/400/560'],
    imageHint: 'hockey captain',
  },
  // Additional products to fill "New & Trending"
  {
    id: 'prod_101',
    name: 'Retro Film Camera',
    description: 'A fully mechanical 35mm film camera. Perfect for students and enthusiasts.',
    price: 150.0,
    category: 'Vintage',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/filmcamera/600/600'],
    imageHint: 'camera',
  },
  {
    id: 'prod_102',
    name: 'Hand-Knitted Wool Scarf',
    description: 'Warm and cozy wool scarf, knitted by hand. Available in earth tones.',
    price: 45.0,
    category: 'Fashion',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/woolscarf/600/800'],
    imageHint: 'scarf',
  },
  {
    id: 'prod_103',
    name: 'Oak Coffee Table',
    description: 'Solid oak coffee table with a mid-century modern design.',
    price: 280.0,
    category: 'Home & Living',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/coffeetable/800/600'],
    imageHint: 'table',
  },
  {
    id: 'prod_104',
    name: 'Vintage Typewriter',
    description: 'Working condition typewriter from the 1960s. Includes fresh ribbon.',
    price: 120.0,
    category: 'Vintage',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/typewriter/600/600'],
    imageHint: 'typewriter',
  },
  {
    id: 'prod_105',
    name: 'Ceramic Plant Pot',
    description: 'Hand-glazed ceramic pot, perfect for indoor plants.',
    price: 25.0,
    category: 'Home & Living',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/plantpot/600/600'],
    imageHint: 'plant pot',
  },
  {
    id: 'prod_106',
    name: 'Leather Messenger Bag',
    description: 'Durable leather bag for work or travel. Fits a 15-inch laptop.',
    price: 180.0,
    category: 'Fashion',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/messengerbag/600/600'],
    imageHint: 'bag',
  },
  {
    id: 'prod_107',
    name: 'Abstract Sculpture',
    description: 'Modern abstract sculpture made from reclaimed metal.',
    price: 400.0,
    category: 'Home & Living',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/sculpture/600/800'],
    imageHint: 'sculpture',
  },
  {
    id: 'prod_108',
    name: 'Vintage Denim Jacket',
    description: 'Oversized denim jacket from the 90s.',
    price: 65.0,
    category: 'Fashion',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/denimjacket/600/800'],
    imageHint: 'denim',
  },
  {
    id: 'prod_109',
    name: 'Handmade Soap Set',
    description: 'Set of 3 natural soaps with essential oils.',
    price: 18.0,
    category: 'Handmade',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/soap/600/600'],
    imageHint: 'soap',
  },
  {
    id: 'prod_110',
    name: 'Bamboo Cutting Board',
    description: 'Eco-friendly bamboo cutting board. Durable and easy to clean.',
    price: 30.0,
    category: 'Home & Living',
    sellerId: 'user_2',
    imageUrls: ['https://picsum.photos/seed/cuttingboard/600/600'],
    imageHint: 'cutting board',
  },
  {
    id: 'prod_111',
    name: 'Vintage Map Print',
    description: 'Reproduction of an 18th-century world map.',
    price: 40.0,
    category: 'Vintage',
    sellerId: 'user_3',
    imageUrls: ['https://picsum.photos/seed/map/800/600'],
    imageHint: 'map',
  },
  {
    id: 'prod_112',
    name: 'Woven Wall Hanging',
    description: 'Macrame wall hanging to add texture to your room.',
    price: 55.0,
    category: 'Handmade',
    sellerId: 'user_1',
    imageUrls: ['https://picsum.photos/seed/macrame/600/800'],
    imageHint: 'macrame',
  },
];

export const auctions: Auction[] = [
  {
    id: 'auc_1',
    name: 'Antique Pocket Watch',
    description:
      'A beautiful gold-plated pocket watch from the early 1900s. In working condition.',
    currentBid: 250.0,
    bids: 12,
    timeLeft: '2h 15m',
    sellerId: 'user_3',
    imageUrl: 'https://picsum.photos/seed/pocketwatch/600/600',
    imageHint: 'pocket watch',
  },
  {
    id: 'auc_2',
    name: 'Signed First Edition Book',
    description:
      "A rare, signed first edition of a classic novel. A true collector\'s item.",
    currentBid: 475.0,
    bids: 23,
    timeLeft: '1d 5h',
    sellerId: 'user_3',
    imageUrl: 'https://picsum.photos/seed/firstedition/600/800',
    imageHint: 'old book',
  },
  {
    id: 'auc_3',
    name: 'Limited Edition Art Print',
    description:
      'A limited edition print from a renowned artist. Only 50 were made. Comes with a certificate of authenticity.',
    currentBid: 120.0,
    bids: 8,
    timeLeft: '4h 30m',
    sellerId: 'user_1',
    imageUrl: 'https://picsum.photos/seed/artprint/700/700',
    imageHint: 'art print',
  },
  {
    id: 'auc_4',
    name: 'Vintage Film Camera',
    description:
      'A classic 35mm film camera from the 1970s. Fully tested and functional. A great camera for film photography enthusiasts.',
    currentBid: 85.0,
    bids: 15,
    timeLeft: '8h 5m',
    sellerId: 'user_3',
    imageUrl: 'https://picsum.photos/seed/filmcamera/600/600',
    imageHint: 'film camera',
  },
];

// Simulate a network request to get products with pagination
export const getProductsLegacy = (
  page: number,
  limit: number,
  blockedSellerIds: string[] = []
): Promise<{ products: Product[]; hasMore: boolean }> => {
  return new Promise(resolve => {
    setTimeout(() => {
      const publicProducts = products.filter(p => !p.isPrivate && !blockedSellerIds.includes(p.sellerId) && p.category !== 'Collector Cards');
      const start = (page - 1) * limit;
      const end = page * limit;
      const paginatedProducts = publicProducts.slice(start, end);
      const hasMore = end < publicProducts.length;
      resolve({ products: paginatedProducts, hasMore });
    }, 500);
  });
};

// Simulate a network request
export const getAuctions = (): Promise<Auction[]> => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(auctions);
    }, 1000);
  });
};

// Simulate getting a product by ID
export const getProductByIdLegacy = (id: string): Promise<Product | undefined> => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(products.find(p => p.id === id));
    }, 300);
  });
};
